// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDApc1_n2kgTrVH3iHZGcr7EescrzRddNY',
    appId: '1:592920164471:web:8cca322e0bc2459db96e72',
    messagingSenderId: '592920164471',
    projectId: 'flutter-learn-5a829',
    authDomain: 'flutter-learn-5a829.firebaseapp.com',
    storageBucket: 'flutter-learn-5a829.firebasestorage.app',
    measurementId: 'G-C03RFNXCGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDszNgYvDB_Ke1kaJuYIXM2pXv895T9F6s',
    appId: '1:592920164471:android:ddda4182fef8d19eb96e72',
    messagingSenderId: '592920164471',
    projectId: 'flutter-learn-5a829',
    storageBucket: 'flutter-learn-5a829.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4BKsSBn7bQLYzWvInB5whtSJraKsjVxs',
    appId: '1:592920164471:ios:dae6fd029797e02db96e72',
    messagingSenderId: '592920164471',
    projectId: 'flutter-learn-5a829',
    storageBucket: 'flutter-learn-5a829.firebasestorage.app',
    iosBundleId: 'com.example.flutterProviderFirebase',
  );
}
